from mobile_de_selenium_code_prod_local_single_func import mobile_de_local_single_func

def main():
    mobile_de_local_single_func(
        category="cat_1",
        car_list=[
            "ALPINA",
            "Aston Martin",
            "Bentley",
            "Bugatti",
            "Ferrari",
            "Gemballa",
            "Koenigsegg",
            "KTM",
            "Lamborghini",
            "Maybach",
            "McLaren",
            "Pagani",
            "Rolls-Royce",
            "Ruf",
            "Techart",
            "Wiesmann",
        ],
        modell_list=[
            # Alpina
            "B10",
            "B12",
            "B3",
            "B4",
            "B5",
            "B6",
            "B7",
            "B8",
            "D10",
            "D3",
            "D4",
            "D5",
            "Roadster S",
            "XB7",
            "XD3",
            "XD4",

            # Aston Martin
            "AR1",
            "Cygnet",
            "DB",
            "DB11",
            "DB7",
            "DB9",
            "DBS",
            "DBX",
            "Lagonda",
            "Rapide",
            "V12 Vantage",
            "V8 Vantage",
            "Vanquish",
            "Virage",

            # Bentley
            "Arnage",
            "Bentayga",
            "Brooklands",
            "    Continental Flying Spur",
            "    Continental GT",
            "    Continental GTC",
            "    Continental Supersports",
            "Eight",
            "Flying Spur",
            "Mulsanne",
            "Turbo R",
            "Turbo RT",
            "Turbo S",

            # Bugatti
            "Chiron",
            "EB 110",
            "Veyron",

            # Ferrari
            "208",
            "246",
            "250",
            "275",
            "288",
            "296 GTB",
            "308",
            "328",
            "330",
            "348",
            "360",
            "365",
            "400",
            "412",
            "456",
            "458",
            "488 GTB",
            "488 Pista",
            "488 Spider",
            "512",
            "550",
            "575",
            "599 GTB",
            "599 GTO",
            "599 SA Aperta",
            "612",
            "750",
            "812",
            "California",
            "Daytona",
            "Dino GT4",
            "Enzo Ferrari",
            "F12",
            "F355",
            "F40",
            "F430",
            "F50",
            "F8",
            "FF",
            "GTC4Lusso",
            "LaFerrari",
            "Mondial",
            "Portofino",
            "Purosangue",
            "Roma",
            "SF90",
            "Superamerica",
            "Testarossa",

            # Gemballa
            "Beliebig"

            # Koenigsegg
            "Agera",
            "CCR",
            "CCXR",

            # KTM
            "X-BOW",

            # Lamborghini
            "Aventador",
            "Countach",
            "Diablo",
            "Espada",
            "Gallardo",
            "Huracán",
            "Jalpa",
            "LM",
            "Miura",
            "Murciélago",
            "Urraco",
            "Urus",

            # Maybach
            "57",
            "62",
            "Pullman",
            
            # McLaren
            "540C",
            "570GT",
            "570S",
            "600LT",
            "620R",
            "650S",
            "650S Coupé",
            "650S Spider",
            "675LT",
            "675LT Spider",
            "720S",
            "765",
            "765LT",
            "Artura",
            "Elva",
            "GT",
            "MP4-12C",
            "P1",
            "Senna GTR",
            "Speedtail",
            
            # Pagani
            "Huayra",
            "Zonda",
            
            # Rolls-Royce
            "Corniche",
            "Cullinan",
            "Dawn",
            "Flying Spur",
            "Ghost",
            "Park Ward",
            "Phantom",
            "Silver Cloud",
            "Silver Dawn",
            "Silver Seraph",
            "Silver Shadow",
            "Silver Spirit",
            "Silver Spur",
            "Wraith",

            # Wiesmann
            "MF 25",
            "MF 28",
            "MF 3",
            "MF 30",
            "MF 35",
            "MF 4",
            "MF 5",
            "Andere",
        ]
    )

if __name__ == '__main__':
    main()